# Typical laptop setup, with wifi, brightness, battery etc, for
# i3/Sway.

# For X11/i3, you'll want to replace calls to swaymsg with i3-msg, and
# the sway-xkb module with the xkb module.

# fonts we'll be re-using here and there
awesome: &awesome Font Awesome 5 Free:style=solid:pixelsize=14
awesome_brands: &awesome_brands Font Awesome 5 Brands:pixelsize=16

std_underline: &std_underline {underline: { size: 2, color: 0066ffff}}

# This is THE bar configuration
bar:
  height: 26
  location: top
  spacing: 5
  margin: 7

  # Default font
  font: JetBrains Mono:pixelsize=14

  foreground: ffffffff
  background: 111111cc

  border:
    color: 999999cc
    top-margin: 0

  left:
    - i3:
        sort: ascending
        anchors:
          - string: &i3_common {margin: 5, on-click: "swaymsg --quiet workspace {name}"}
          - string: &default   {<<: *i3_common, text: "{name}"}
          - string: &1         {<<: *i3_common, text: , font: *awesome}
          - string: &2         {<<: *i3_common, text: , font: *awesome}
          - string: &3         {<<: *i3_common, text: , font: *awesome}
          - string: &4         {<<: *i3_common, text: , font: *awesome}
          - focused: &focused
              deco: {stack: [background: {color: 0000994c}, <<: *std_underline]}
          - invisible: &invisible {foreground: ffffff55}
          - urgent: &urgent
              foreground: 000000ff
              deco: {stack: [background: {color: bc2b3fff}, <<: *std_underline]}
        content:
          "":
            map:
              tag: state
              values:
                focused:   {string: {<<: [*default, *focused]}}
                unfocused: {string: {<<: *default}}
                invisible: {string: {<<: [*default, *invisible]}}
                urgent:    {string: {<<: [*default, *urgent]}}
          1:
            map:
              tag: state
              values:
                focused:   {string: {<<: [*1, *focused]}}
                unfocused: {string: {<<: *1}}
                invisible: {string: {<<: [*1, *invisible]}}
                urgent:    {string: {<<: [*1, *urgent]}}
          2:
            map:
              tag: state
              values:
                focused:   {string: {<<: [*2, *focused]}}
                unfocused: {string: {<<: *2}}
                invisible: {string: {<<: [*2, *invisible]}}
                urgent:    {string: {<<: [*2, *urgent]}}
          3:
            map:
              tag: state
              values:
                focused: {string: {<<: [*3, *focused]}}
                unfocused: {string: {<<: *3}}
                invisible: {string: {<<: [*3, *invisible]}}
                urgent:    {string: {<<: [*3, *urgent]}}
          4:
            map:
              tag: state
              values:
                focused: {string: {<<: [*4, *focused]}}
                unfocused: {string: {<<: *4}}
                invisible: {string: {<<: [*4, *invisible]}}
                urgent:    {string: {<<: [*4, *urgent]}}


  

  right:
    - removables:
        anchors:
          drive: &drive { text: , font: *awesome}
          optical: &optical {text: , font: *awesome}
        spacing: 5
        content:
          map:
            tag: mounted
            values:
              false:
                map:
                  tag: optical
                  on-click: udisksctl mount -b {device}
                  values:
                    false: [{string: *drive}, {string: {text: "{label}"}}]
                    true: [{string: *optical}, {string: {text: "{label}"}}]
              true:
                map:
                  tag: optical
                  on-click: udisksctl unmount -b {device}
                  values:
                    false:
                      - string: {<<: *drive, deco: *std_underline}
                      - string: {text: "{label}"}
                    true:
                      - string: {<<: *optical, deco: *std_underline}
                      - string: {text: "{label}"}
    - sway-xkb:
        identifiers: [1:1:AT_Translated_Set_2_keyboard]
        content:
          - string: {text: , font: *awesome}
          - string: {text: "{layout}"}


    - battery:
        name: BAT0
        poll-interval: 30
        content:
          map:
            tag: state
            values:
              discharging:
                - ramp:
                    tag: capacity
                    items:
                      - string: {text: , foreground: ff0000ff, font: *awesome}
                      - string: {text: , foreground: ffa600ff, font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , font: *awesome}
                      - string: {text: , foreground: 00ff00ff, font: *awesome}
                - string: {text: "{capacity}% {estimate}"}
              charging:
                - string: {text: , foreground: 00ff00ff, font: *awesome}
                - string: {text: "{capacity}% {estimate}"}
              full:
                - string: {text: , foreground: 00ff00ff, font: *awesome}
                - string: {text: "{capacity}% full"}
    - clock:
        time-format: "%H:%M %Z"
        content:
          - string: {text: , font: *awesome}
          - string: {text: "{date}", right-margin: 5}
          - string: {text: , font: *awesome}
          - string: {text: "{time}"}
    - label:
        content:
          string:
            on-click: loginctl poweroff
            text: 
            font: *awesome